### ISSUE TITLE
[Feature]: Implementing a Parsing

### ISSUE THREAD

**Issue by idealflower-k** [jgodv/miniRT#1]
### **Package Scope**

-   [x] New package

Package name: parser

### **Overview**

-   [x] Receives files with a ".rt" extension.
-   [x] Splits elements based on one or more line breaks.
-   [x] Splits element types based on one or more spaces.
-   [x] Validates the type.
-   [x] If an incorrect configuration is found, the program terminates and returns "Error\n" along with a clear error message.

### **Describe the solution you'd like**

-   [x] Stores the data obtained through parsing in a t_meta
-   [x] Handles errors appropriately.

### **Additional context**

-   [x] The structures and functions used are defined on the notion page.

### **dependence on this issue**
- [x] #2 
- [x] #8 
- [x] #13

**Comment by jgodv** [comment]
1. spot_light 연결리스트로 구현.
